### ISSUE TITLE
Unable to install tar.gz in environments without access to global pypi.  Please, consider building py2 wheels

### ISSUE THREAD

**Issue by lorochka85** [zalando/python-clickclick#12]
Due to current pip/setuptools behavior packages listed in setup_requires are always downloaded from global pypi, regardless of index argument passed to pip install (please, see https://github.com/pypa/setuptools/issues/209) for more details.   This makes it impossible to install   source distribution in environments without access to global pypi on python2.7.

* The easier fix: 
add `setup.cfg` to the project with the following content:

```
[bdist_wheel]
universal=1
```

This will result in release.sh producing py2py3 wheel (just like click project) and the wheel doesn't suffer from the setuptools bug mentioned above. 

* The harder fix:
figure which setup.py commands need ['six', 'flake8']  and do something along the lines of 
```
import sys
...
need = {'clean', 'flake8', 'test'}.intersection(sys.argv)
setup_requires = ['six', 'flake8'] if need else []
```

Thank you!

**Comment by hjacobs** [comment]
Thanks for the info, I'm not using Python 2 anymore... :smile: 

Are you willing to do a PR?

**Comment by lorochka85** [comment]
Ha, that is true, metadata states only py3.  But it works in 2.7, we tested ;)
Will be happy to PR.  Thank you for addressing this issue so fast!

**Comment by hjacobs** [comment]
@lorochka85 saw your issue for Connexion (https://github.com/zalando/connexion/issues/488), feel free to do a PR there, too. Thanks!

**Comment by hjacobs** [comment]
Fixed and released: https://github.com/zalando/python-clickclick/releases/tag/1.2.2
