### ISSUE TITLE
Optionally accept adding new line after Action message

### ISSUE THREAD

**Issue by mohabusama** [zalando/python-clickclick#6]
I might be missing other workaround, assuming the following:

```python
with Action('Get stuff ...'):
    print(yaml_stuff)
```

the output will look like:
```
Get stuff ...id: yaml-obj-id
key: value

OK
```

I suggest adding `nl=False` to `Action`, as in case it was `True` it would always append a new line to the end of the action message. (this ofc instead of always calling print/secho new line in Action block)

**Comment by hjacobs** [comment]
Yes, makes sense --- easy enough :smile:

**Comment by hjacobs** [comment]
I'm fine with adding `nl=False`.
